### ISSUE TITLE
Boostrap

### ISSUE THREAD

**Issue by profesorfaco** [Litidos/Examen#1]
Convendría revisar pauta de evaluación:

> Estructura y código fuente. **Usa Bootstrap** para implementar un diseño responsivo, con una redacción de código que resulta precisa y concisa. En la cabeza (head) cuida los metadatos. Y dentro del cuerpo (body), se reconocen claramente tres secciones, el encabezado (header), el contenido principal (main) y el pie de página (footer; y este se ajusta al modelo acordado por el curso) ¡Es muy recomendable aprovechar la [organización preparada en los snippets](https://github.com/profesorfaco/dno075-2020/blob/gh-pages/clase-16/snippets/organizacion.html) y limpiar el resultado con [HTML Formatter](https://webformatter.com/html)!

La pauta está en https://github.com/profesorfaco/dno075-2020/blob/gh-pages/clase-17/README.md

**Comment by fjgajardo** [comment]
No hay opción? Puedo programar lo que va faltando con bootstrap y dejar lo que ya estaba con tailwind CSS? 
De no ser posible, el resto del punto aun cuando no se use bootstrap se puede lograr? Por tiempo ya no me da para cambiarlo a bootstrap (Osea voy a tratar) y al menos estoy cumpliendo con lo responsivo y puedo preocuparme de que esté mejor definidas las partes enumeradas en la pauta con sus tag correspondientes.

**Comment by profesorfaco** [comment]
Hola. Tengo 3 contra-argumentos: 

- Desde la clase 1 usamos Bootstrap… y en un examen corresponde "comprobar o demostrar el aprovechamiento en los estudios" (esto copiado de la RAE). 

- Se les dejó todo listo en los [*snippets* compartidos en la clase-16](https://github.com/profesorfaco/dno075-2020/tree/gh-pages/clase-16), con la indicación: "Estos snippets suponen el uso de Bootstrap, herramienta que hemos aprovechado en cada clase del OPR."

- Son 3 integrantes por equipo. Como equipo deberían organizar su tiempo, ayudarse a resolver las dificultades individuales (si 1 tiene tiempo en contra, hay 2 más). 

Considerando los 3 contra-argumentos: Sí,  es muy necesario usar Bootstrap.

**Comment by fjgajardo** [comment]
Ok!
